tasks:
  - before: |
      wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${GRAALVM_VERSION}/graalvm-ce-java11-linux-amd64-${GRAALVM_VERSION}.tar.gz -O /tmp/graalvm.tar.gz
      tar -xzf /tmp/graalvm.tar.gz -C /usr/bin
      ln -s /usr/bin/graalvm-ce-java11-${GRAALVM_VERSION} /usr/bin/graalvm
    init: |
      cd /workspace
      git clone --branch graalvm https://github.com/KengoTODA/spotbugs.git
      cd /workspace/spotbugs-cli
      ./gradlew build nativeImage
    env:
      GRAALVM_VERSION: "21.1.0"
      JAVA_HOME: "/usr/bin/graalvm"

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-debug
    - mathiasfrohlich.kotlin
