image: ghcr.io/graalvm/graalvm-ce:java11-21.1.0

tasks:
  - before: cd /workspace && git checkout https://github.com/KengoTODA/spotbugs.git && cd /workspace/spotbugs && git checkout graalvm
    init: ./gradlew build nativeImage

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-debug
