name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.1.0
          native-image: true
      - run: |
          ./gradlew spotlessCheck build --no-daemon
          ls $JAVA_HOME/lib
          ls build/libs
          ./gradlew nativeImage --no-daemon
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: build/reports
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: executables
          path: build/executables
