name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: |
          ./gradlew spotlessCheck build --no-daemon
        env:
          TIMEZONEDB_KEY: ${{ secrets.TIMEZONEDB_KEY }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: build/reports
