name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: gradle
      - run: |
          ./gradlew spotlessCheck build --no-daemon
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: build/reports
